apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: java-application  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-application
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
      - name: java-application
        image: kaytheog/java:69
        resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "128Mi"
              cpu: "512m"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: java-application-service
spec:
  selector:
    app: java-application
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

